[package]
name = "srv-iface"
version = "0.1.0"
edition.workspace = true

[dependencies]
common = { workspace = true }
linkme = { workspace = true }
spin = { workspace = true }
num_enum = { version = "0.7.3", default-features = false }
