[env]
RUST_TARGET_PATH = { value = "support/targets", relative = true }
SEL4_PREFIX = { value = ".env/seL4", relative = true }

[build]
target = "aarch64-sel4"

[unstable]
unstable-options = true
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
