[package]
name = "uart-thread"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4 = { workspace = true }
sel4-logging = { workspace = true }
sel4-kit = { workspace = true }
sel4-runtime = { workspace = true }
spin = { workspace = true }
log = "0.4"
common = { workspace = true }
crate-consts = { workspace = true }
slot-manager = { workspace = true }
arm_pl011 = { git = "https://github.com/Byte-OS/arm_pl011.git", rev = "8a66e24" }
