#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[package]
name = "kernel-thread"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4 = { workspace = true }
sel4-ctors-dtors = { workspace = true }
sel4-panicking = { workspace = true, features = ["alloc"] }
sel4-panicking-env = { workspace = true }
sel4-logging = { workspace = true }
sel4-dlmalloc = { workspace = true }
sel4-sync = { workspace = true }
sel4-runtime-common = { workspace = true, features = [
  "start",
  "tls",
  "unwinding",
] }
spin = { workspace = true }
log = "0.4"
xmas-elf = "0.9.1"
syscalls = { version = "0.6", default-features = false }
sel4-elf-header = { workspace = true }
sel4-initialize-tls = { workspace = true }
sel4-stack = { workspace = true }
sel4-root-task = { workspace = true }
bitflags = "2.6"
memory_addr = "0.3"
axerrno = "0.1"
num_enum = { version = "0.7", default-features = false }
object = { version = "0.36.1", default-features = false, features = ["read"] }

common = { workspace = true }
crate-consts = { workspace = true }
slot-manager = { workspace = true }

include_bytes_aligned = "0.1.3"
